name: flutter_sane_lints
description: A custom lint for flutter projects to avoid ad-hoc string literals.
version: 0.2.1
repository: https://github.com/gbassisp/extra_lints

environment:
  sdk: ">=2.12.0 <4.0.0"

dev_dependencies:
  # build_runner: ^2.0.0
  coverage: ^1.0.0
  mockito: ^5.0.0
  mocktail: ^0.3.0
  test: ^1.0.0
  very_good_analysis: 

dependencies:
  analyzer: ^5.0.0
  custom_lint_builder: ^0.5.0
  meta: ^1.0.0